backend:
  name: git-gateway
  branch: main # Branch to update (defaults to master)

# Publish mode options:
publish_mode: simple

# Media folder where uploaded images will be saved
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Collections define the structure for content types
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "index.html"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Description", name: "hero_description", widget: "text"}
          - {label: "About Section Title", name: "about_title", widget: "string"}
          - {label: "About Section Text", name: "about_text", widget: "text"}
      
      - name: "about"
        label: "About Page"
        file: "about.html"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Mission Statement", name: "mission", widget: "text"}
          - {label: "Vision", name: "vision", widget: "text"}
          - {label: "Team Description", name: "team", widget: "markdown"}
          
      - name: "media"
        label: "Media Page"
        file: "media.html"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Description", name: "description", widget: "text"}
          - {label: "Featured Media Title", name: "featured_title", widget: "string"}
          - {label: "Media Content", name: "media_content", widget: "markdown"}
          
      - name: "contact"
        label: "Contact Page"
        file: "contact.html"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Contact Information", name: "contact_info", widget: "text"}
          - {label: "Form Instructions", name: "form_instructions", widget: "text"}
